# Generated by Django 4.1.4 on 2022-12-24 06:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('po', 'po'), ('json', 'json')], max_length=10)),
                ('file', models.FileField(upload_to='po_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['po', 'json'])])),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('result_file', models.URLField(blank=True, null=True)),
                ('from_lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('cry', 'Cyrillic')], max_length=10)),
                ('to_lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('cry', 'Cyrillic')], max_length=10)),
                ('execution_time', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
