# Generated by Django 4.1.4 on 2022-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofile',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pofile',
            name='from_lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('cry', 'Cyrillic'), ('kaa', 'Karakalpak')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pofile',
            name='to_lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek'), ('cry', 'Cyrillic'), ('kaa', 'Karakalpak')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pofile',
            name='type',
            field=models.CharField(choices=[('po', 'PO'), ('json', 'JSON')], max_length=10),
        ),
    ]
