# Generated by Django 4.1.4 on 2023-05-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_file_user_alter_file_result_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('po', 'Po'), ('json', 'Json')], default='po', max_length=255),
            preserve_default=False,
        ),
    ]
