# Generated by Django 4.1.4 on 2023-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="execution_time",
            field=models.IntegerField(default=0),
        ),
    ]
